export const ALL_SHIPPERS_REQUEST = "ALL_SHIPPERS_REQUEST";
export const ALL_SHIPPERS_SUCCESS = "ALL_SHIPPERS_SUCCESS";
export const ALL_SHIPPERS_FAIL = "ALL_SHIPPERS_FAIL";

export const SHIPPER_DETAILS_REQUEST = "SHIPPER_DETAILS_REQUEST";
export const SHIPPER_DETAILS_SUCCESS = "SHIPPER_DETAILS_SUCCESS";
export const SHIPPER_DETAILS_FAIL = "SHIPPER_DETAILS_FAIL";

export const ADMIN_SHIPPERS_REQUEST = "ADMIN_SHIPPERS_REQUEST";
export const ADMIN_SHIPPERS_SUCCESS = "ADMIN_SHIPPERS_SUCCESS";
export const ADMIN_SHIPPERS_FAIL = "ADMIN_SHIPPERS_FAIL";

export const NEW_SHIPPER_REQUEST = "NEW_SHIPPER_REQUEST";
export const NEW_SHIPPER_SUCCESS = "NEW_SHIPPER_SUCCESS";
export const NEW_SHIPPER_RESET = "NEW_SHIPPER_RESET";
export const NEW_SHIPPER_FAIL = "NEW_SHIPPER_FAIL";

export const UPDATE_SHIPPER_REQUEST = "UPDATE_SHIPPER_REQUEST";
export const UPDATE_SHIPPER_SUCCESS = "UPDATE_SHIPPER_SUCCESS";
export const UPDATE_SHIPPER_RESET = "UPDATE_SHIPPER_RESET";
export const UPDATE_SHIPPER_FAIL = "UPDATE_SHIPPER_FAIL";

export const DELETE_SHIPPER_REQUEST = "DELETE_SHIPPER_REQUEST";
export const DELETE_SHIPPER_SUCCESS = "DELETE_SHIPPER_SUCCESS";
export const DELETE_SHIPPER_RESET = "DELETE_SHIPPER_RESET";
export const DELETE_SHIPPER_FAIL = "DELETE_SHIPPER_FAIL";

export const LOAD_SHIPPER_SUCCESS = "LOAD_SHIPPER_SUCCESS";
export const LOAD_SHIPPER_FAIL = "LOAD_SHIPPER_FAIL";
export const LOAD_SHIPPER_REQUEST = "DELETE_SHIPPER_REQUEST";

export const REMOVE_SHIPPER_DETAILS = "REMOVE_SHIPPER_DETAILS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";