export const ALL_SHOPS_REQUEST = "ALL_SHOPS_REQUEST";
export const ALL_SHOPS_SUCCESS = "ALL_SHOPS_SUCCESS";
export const ALL_SHOPS_FAIL = "ALL_SHOPS_FAIL";

export const SHOP_DETAILS_REQUEST = "SHOP_DETAILS_REQUEST";
export const SHOP_DETAILS_SUCCESS = "SHOP_DETAILS_SUCCESS";
export const SHOP_DETAILS_FAIL = "SHOP_DETAILS_FAIL";

export const ADMIN_SHOPS_REQUEST = "ADMIN_SHOPS_REQUEST";
export const ADMIN_SHOPS_SUCCESS = "ADMIN_SHOPS_SUCCESS";
export const ADMIN_SHOPS_FAIL = "ADMIN_SHOPS_FAIL";

export const NEW_SHOP_REQUEST = "NEW_SHOP_REQUEST";
export const NEW_SHOP_SUCCESS = "NEW_SHOP_SUCCESS";
export const NEW_SHOP_RESET = "NEW_SHOP_RESET";
export const NEW_SHOP_FAIL = "NEW_SHOP_FAIL";

export const UPDATE_SHOP_REQUEST = "UPDATE_SHOP_REQUEST";
export const UPDATE_SHOP_SUCCESS = "UPDATE_SHOP_SUCCESS";
export const UPDATE_SHOP_RESET = "UPDATE_SHOP_RESET";
export const UPDATE_SHOP_FAIL = "UPDATE_SHOP_FAIL";

export const DELETE_SHOP_REQUEST = "DELETE_SHOP_REQUEST";
export const DELETE_SHOP_SUCCESS = "DELETE_SHOP_SUCCESS";
export const DELETE_SHOP_RESET = "DELETE_SHOP_RESET";
export const DELETE_SHOP_FAIL = "DELETE_SHOP_FAIL";

export const LOAD_SHOP_SUCCESS = "LOAD_SHOP_SUCCESS";
export const LOAD_SHOP_FAIL = "LOAD_SHOP_FAIL";
export const LOAD_SHOP_REQUEST = "DELETE_SHOP_REQUEST";

export const REMOVE_SHOP_DETAILS = "REMOVE_SHOP_DETAILS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";